kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "demo-app.fullname" . }}-app-config
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
data:
  connection-string: {{ .Values.faultInjection.toggler.value1 | quote }}
