apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}-app-script
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
type: Opaque
data:
  webserver.sh: {{ tpl (.Files.Get "files/webserver.sh") . | b64enc }}
