{{- if not (lookup "v1" "Namespace" "" .Values.faultInjection.namespace ) }}
{{- if .Values.faultInjection.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "demo-app.faultInjection.namespace" . }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
{{- end }}
