apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "demo-app.fullname" . }}-manage-config
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["{{ include "demo-app.fullname" . }}-app-config"]
  verbs: ["get", "list", "update", "patch"]
