{{- if .Values.faultInjection.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo-app.serviceAccountName" . }}
  namespace: {{ include "demo-app.faultInjection.namespace" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
  {{- with .Values.faultInjection.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.faultInjection.serviceAccount.automount }}
{{- end }}
