apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}-toggler-script
  namespace: {{ include "demo-app.faultInjection.namespace" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
type: Opaque
data:
  toggle-configmap.sh: {{ tpl (.Files.Get "files/toggle.sh") . | b64enc }}
