apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
  namespace: {{ .Values.workload_namespace }}
  labels:
    app: reporting
spec:
  selector:
    matchLabels:
      app: reporting
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: nginx
          image: nginx

