{{- if .Values.require_annotations_pattern.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-annotations
  annotations:
    policies.kyverno.io/title: Require Annotations
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, Annotation
    policies.kyverno.io/description: >-
      Define and use annotations that identify semantic attributes of your application or Deployment.
      A common set of annotations allows tools to work collaboratively, describing objects in a common manner that
      all tools can understand. The recommended annotations describe applications in a way that can be
      queried. This policy validates that the annotation `corp.org/department` is specified with some value.            
spec:
  validationFailureAction: audit # https://kyverno.io/docs/writing-policies/validate/#validation-failure-action
  background: true
  rules:
  - name: require-annotation
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaceSelector:
              matchExpressions:
                - key: app 
                  operator: In
                  values:
                  - {{ .Values.workload_namespace }}

    validate:
      message: "The annotation `team` is required."
      pattern:
        metadata:
          annotations:
            team: "?*"
{{- end }}
{{- if .Values.require_ownership_label_pattern.enabled }}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-dt-ownership
  annotations:
    policies.kyverno.io/title: Require Dynatrace Ownership
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Workload, Label
    policies.kyverno.io/description: >-
      Ownership of workloads within Dynatrace can be configured using the "dt.owner" label on the workload entity.            
spec:
  validationFailureAction: Audit # https://kyverno.io/docs/writing-policies/validate/#validation-failure-action
  background: true
  rules:
  - name: require-dt-ownership
    match:
      any:
      - resources:
          kinds:
          - Deployment
          - StatefulSet
          - DaemonSet
          namespaceSelector:
              matchExpressions:
                - key: dynatrace.com/ownership-required 
                  operator: Exists
    validate:
      message: "The label `dt.owner` is required. Read more about it here: https://www.dynatrace.com/support/help/manage/ownership/assign-ownership#kubernetes"
      pattern:
        metadata:
          labels:
            # ToDo: support multip ownership (dt.owner-1:, dt.owner-2:, ...)
            dt.owner: "?*"
{{- end }}
{{- if .Values.require_requests_pattern.enabled }}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-requests
  annotations:
    policies.kyverno.io/title: Require requests
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod, Requests
    policies.kyverno.io/description: >-
      Setting requests on pods is considered best-practices in Kubernetes.            
spec:
  validationFailureAction: Audit # https://kyverno.io/docs/writing-policies/validate/#validation-failure-action
  background: true
  rules:
  - name: require-requests
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaceSelector:
              matchExpressions:
                - key: dynatrace.com/requests-required 
                  operator: Exists

    validate:
      message: "Requests for CPU and Memory are required."
      pattern:
        spec:
          containers:
          - resources:
              requests:
                memory: "?*"
                cpu: "?*"

{{- end }}