{{- $namespace := .Values.namespace | default .Release.Namespace }}
{{- if $namespace }}
{{- $lookupResult := lookup "v1" "Namespace" "" $namespace }}
  {{- if not $lookupResult }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}
  {{- end}}
{{- end }}