apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-pressure
spec:
  selector:
    matchLabels:
      app: node-pressure
  replicas: 1
  template:
    metadata:
      labels:
        app: node-pressure
      annotations:
        oneagent.dynatrace.com/inject: "false"
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      serviceAccountName: node-pressure
      containers:
      - name: node-pressure
        image: alpine
        command: ["sh", "-c", "apk update && apk add curl stress-ng kubectl && sleep 10 && if [[ $(kubectl get node $NODE_NAME -o jsonpath='{.status.conditions[?(@.type==\"MemoryPressure\")].status}') == \"False\" ]]; then echo \"No pressure; allocating memory\"; stress-ng --vm 1 --vm-bytes 5g --vm-hang 0; else echo \"Sleeping...\" && sleep 9999999999999999; fi"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        restartPolicy: Always
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps -ef | grep stress | grep -v grep"
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps -ef | grep stress | grep -v grep"
          initialDelaySeconds: 120
          periodSeconds: 5
