apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.faultInjection.nameOverride }}
spec:
  selector:
    matchLabels:
      demo: node-pressure
  replicas: 1
  template:
    metadata:
      labels:
        demo: node-pressure
      annotations:
        oneagent.dynatrace.com/inject: "false"
    spec:
      containers:
        - name: {{ .Values.faultInjection.nameOverride }}
          image: alpine
          command:
            - sh
            - /script/script.sh
          volumeMounts:
            - name: script
              mountPath: /script
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps -ef | grep stress | grep -v grep"
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps -ef | grep stress | grep -v grep"
            initialDelaySeconds: 120
            periodSeconds: 5
{{- if .Values.faultInjection.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.faultInjection.nodeSelector | indent 8 }}
{{- end }}
      serviceAccountName: node-pressure
{{- if .Values.faultInjection.tolerations }}
      tolerations:
{{ toYaml .Values.faultInjection.tolerations | indent 6 }}
{{- end}}
      volumes:
      - name: script
        configMap:
          name: script
