apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name | default .Release.Name }}-scale-up
  namespace: {{ .Values.faultInjection.namespace }}
spec:
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  schedule: {{ .Values.faultInjection.schedule.scaleUp | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scale-up
              image: alpine/kubectl:1.34.1
              command:
                - /bin/sh
                - -c
                - |
                  kubectl scale deployment {{ .Values.faultInjection.nameOverride }} --namespace {{ .Values.namespace | default .Release.Namespace }} --replicas={{ .Values.faultInjection.replicas.max }}
          restartPolicy: OnFailure
          serviceAccountName: pending-pod
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name | default .Release.Name }}-scale-down
  namespace: {{ .Values.faultInjection.namespace }}
spec:
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  schedule: {{ .Values.faultInjection.schedule.scaleDown | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scale-down
              image: alpine/kubectl:1.34.1
              command:
                - /bin/sh
                - -c
                - |
                  kubectl scale deployment {{ .Values.faultInjection.nameOverride }} --namespace {{ .Values.namespace | default .Release.Namespace }} --replicas={{ .Values.faultInjection.replicas.min }}
          restartPolicy: OnFailure
          serviceAccountName: pending-pod
