{{ $password := randAlphaNum 8 }}
{{ $secret := (lookup "v1" "Secret" .Release.Namespace "zot-admin") }}
{{ if $secret }}
{{ $password = index $secret.data "admin_password" | b64dec }}
{{ end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: zot-admin
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  htpasswd: {{ htpasswd "admin" $password | quote }}
  admin_password: {{ $password }}
---
kind: Secret
apiVersion: v1
metadata:
  name: zot-admin
  namespace: {{ .Values.faultInjection.namespace }}
type: Opaque
stringData:
  admin_password: {{ $password }}
---
kind: Secret
apiVersion: v1
metadata:
  name: zot-reg-creds
  namespace: {{ .Values.faultInjection.namespace }}
type: Opaque
stringData:
  registry-creds: admin:{{ $password }}
  config.json: |
    {
      "auths": {
        "{{ .Values.faultInjection.nameOverride }}.{{ .Values.namespace | default .Release.Namespace }}:5000": {
          "username": "admin",
          "password": "{{ $password }}"
        }
      }
    }