{{ $password := randAlphaNum 8 }}
---
kind: Secret
apiVersion: v1
metadata:
  name: zot-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  htpasswd: {{ htpasswd "admin" $password | quote }}
  admin_password: {{ $password }}
---
kind: Secret
apiVersion: v1
metadata:
  name: zot-admin
  namespace: {{ .Values.problemPatternsNs }}
type: Opaque
stringData:
  admin_password: {{ $password }}
---
kind: Secret
apiVersion: v1
metadata:
  name: zot-reg-creds
  namespace: {{ .Values.problemPatternsNs }}  
type: Opaque
stringData:
  registry-creds: admin:{{ $password }}
  config.json: |
    {
      "auths": {
        "zot.{{ .Release.Namespace }}:5000": {
          "username": "admin",
          "password": "{{ $password }}"
        }
      }
    }