apiVersion: batch/v1
kind: CronJob
metadata:
  name: exceeded-quota-scale-up-3
  namespace: {{ .Values.faultInjection.namespace }}
spec:
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  schedule: {{ .Values.faultInjection.schedule.scaleUpTo3 | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: exceeded-quota
          containers:
          - name: scale-up
            image: bitnami/kubectl:latest
            args:
              - scale
              - deployment
              - exceeded-quota
              - --replicas=3
              - --namespace={{ .Release.Namespace }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: exceeded-quota-scale-up-4
  namespace: {{ .Values.faultInjection.namespace }}
spec:
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  schedule: {{ .Values.faultInjection.schedule.scaleUpTo4 | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: exceeded-quota
          containers:
          - name: scale-up
            image: bitnami/kubectl:latest
            args:
              - scale
              - deployment
              - exceeded-quota
              - --replicas=4
              - --namespace={{ .Release.Namespace }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: exceeded-quota-scale-down
  namespace: {{ .Values.faultInjection.namespace }}
spec:
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  schedule: {{ .Values.faultInjection.schedule.scaleDown | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: exceeded-quota
          containers:
          - name: scale-down
            image: bitnami/kubectl:latest
            args:
              - scale
              - deployment
              - exceeded-quota
              - --replicas=2
              - --namespace={{ .Release.Namespace }}