apiVersion: batch/v1
kind: CronJob
metadata:
  name: exceeded-quota-scale-up-3
  namespace: {{ .Values.problemPatterns.namespace }}
spec:
  schedule: '0 2 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: exceeded-quota
          containers:
          - name: scale-up
            image: bitnami/kubectl:latest
            args:
              - scale
              - deployment
              - exceeded-quota
              - --replicas=3
              - --namespace={{ .Release.Namespace }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: exceeded-quota-scale-up-4
  namespace: {{ .Values.problemPatterns.namespace }}
spec:
  schedule: '15 5 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: exceeded-quota
          containers:
          - name: scale-up
            image: bitnami/kubectl:latest
            args:
              - scale
              - deployment
              - exceeded-quota
              - --replicas=4
              - --namespace={{ .Release.Namespace }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: exceeded-quota-scale-down
  namespace: {{ .Values.problemPatterns.namespace }}
spec:
  schedule: '30 5 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: exceeded-quota
          containers:
          - name: scale-down
            image: bitnami/kubectl:latest
            args:
              - scale
              - deployment
              - exceeded-quota
              - --replicas=2
              - --namespace={{ .Release.Namespace }}