apiVersion: v1
kind: ServiceAccount
metadata:
  name: exceeded-quota-demo
  namespace: problem-patterns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exceeded-quota-demo-role
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - list
  - get
- apiGroups:
  - "apps"
  resources:
  - deployments/scale
  resourceNames: ["exceeded-quota-demo"]
  verbs:
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: exceeded-quota-demo-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: exceeded-quota-demo-role
subjects:
- kind: ServiceAccount
  name: exceeded-quota-demo
  namespace: problem-patterns