apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.name | default .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  hard:
    limits.cpu: 310m
    limits.memory: 1Gi
    requests.cpu: 310m
    requests.memory: 1Gi