apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.faultInjection.workloadName | default .Release.Name }}-restart-workload
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  schedule: {{ .Values.faultInjection.schedule.killProcess | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: frequent-restarts-for-otel-demo
          containers:
            - name: restart-workload
              image: alpine/kubectl:1.34.1
              command:
                - /bin/sh
                - -c
                - |
                  kubectl exec --namespace {{ .Values.faultInjection.workloadNamespace | default .Release.Namespace }} \
                    {{ .Values.faultInjection.workloadType }}/{{ .Values.faultInjection.workloadName }} -c {{ .Values.faultInjection.containerName }} -- {{ .Values.faultInjection.command }}