apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frequent-restarts-for-otel-demo
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frequent-restarts-for-otel-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: frequent-restarts-for-otel-demo
subjects:
  - kind: ServiceAccount
    name: frequent-restarts-for-otel-demo
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frequent-restarts-for-otel-demo
  namespace: {{ .Release.Namespace }}