apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.faultInjection.nameOverride }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    demo: {{ .Values.name | default .Release.Name }}
spec:
  replicas: {{ .Values.faultInjection.replicas.max }}
  selector:
    matchLabels:
      demo: {{ .Values.name | default .Release.Name }}
  template:
    metadata:
      labels:
        app: nginx
        demo: {{ .Values.name | default .Release.Name }}
      finalizers:
      - finalizer.extensions/v1beta1
    spec:
      containers:
      - name: {{ .Values.faultInjection.nameOverride }}
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        ports:
        - containerPort: 80
