apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    demo: terminating-pod
spec:
  replicas: {{ .Values.faultInjection.replicas.max }}
  selector:
    matchLabels:
      demo: terminating-pod
  template:
    metadata:
      labels:
        app: nginx
        demo: terminating-pod
      finalizers:
      - finalizer.extensions/v1beta1
    spec:
      containers:
      - name: webserver
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        ports:
        - containerPort: 80
