apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
  name: initial-scale-down
  namespace: {{ .Values.faultInjection.namespace }}
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: terminating-pod
      containers:
        - name: scale-down
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl scale deployment webserver-deployment --namespace {{ .Release.Namespace }} --replicas={{ .Values.faultInjection.replicas.min }}
      restartPolicy: OnFailure
