apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
  name: {{ .Values.name | default .Release.Name }}-initial-scale-down
  namespace: {{ .Values.faultInjection.namespace }}
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: scale-down
          image: bitnamilegacy/kubectl:1.33.4
          command:
            - /bin/sh
            - -c
            - |
              kubectl scale deployment {{ .Values.faultInjection.nameOverride }} --namespace {{ .Values.namespace | default .Release.Namespace }} --replicas={{ .Values.faultInjection.replicas.min }}
      restartPolicy: OnFailure
      serviceAccountName: terminating-pod
