apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terminating-pod
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - list
  - get
  - patch
- apiGroups:
  - "apps"
  resources:
  - deployments/scale
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terminating-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terminating-pod
subjects:
- kind: ServiceAccount
  name: terminating-pod
  namespace: {{ .Values.faultInjection.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terminating-pod
  namespace: {{ .Values.faultInjection.namespace }}
