apiVersion: v1
kind: ServiceAccount
metadata:
  name: exceeded-quota-demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exceeded-quota-demo-role
  namespace: exceed-quota
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - list
  - get
- apiGroups:
  - "apps"
  resources:
  - deployments/scale
  verbs:
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exceeded-quota-demo-role-binding
  namespace: exceed-quota
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exceeded-quota-demo-role
subjects:
- kind: ServiceAccount
  name: exceeded-quota-demo
  namespace: problem-patterns